version: "3"
services:
  dogood:
    build: .
    environment:
      NLP_SERVICE: docker.for.mac.host.internal:8000
      LOG_LEVEL: info
      KICKOFF_COUNT: 3
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6.1
    ports:
      - "5453:5432"
