version: "3"
services:
  dogood:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NLP_SERVICE_HOST: http://docker.for.mac.host.internal
      NLP_SERVICE_PORT: 8000
      MAX_CONSUMERS: 20
      # REPLACE_OS_VARS: "true"
    volumes:
      - .:/opt/app
