version: "3"
services:
  feeder:
    build: .
    command: bin/start
    environment:
      FEEDER_ENV: dev
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6.1
    ports:
      - "5443:5432"
