# Build environment
FROM elixir:1.6.1 AS builder

ENV MIX_ENV prod
RUN mix local.hex --force && \
    mix local.rebar --force

WORKDIR /app
COPY . .

RUN rm -rf deps/*
RUN mix deps.get
RUN mix release --env=$MIX_ENV

# Execution environment
FROM elixir:1.6.1

ENV MIX_ENV prod
ENV LANG=C.UTF-8
WORKDIR /app
COPY --from=builder /app/_build/$MIX_ENV/rel/dogood .
CMD ["bin/dogood", "foreground"]
