version: "3"
services:
  dogood:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NLP_SERVICE_HOST: http://docker.for.mac.host.internal
      NLP_SERVICE_PORT: 8000
      DB_NAME: dogood_dev
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      REPLACE_OS_VARS: "true"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6.1
    ports:
      - "5453:5432"
