base: &base
  user: postgres
  password: postgres
  host: postgres
  port: 5432

dev:
  <<: *base
  database: feeder_dev

test:
  <<: *base
  database: feeder_test

production:
  <<: *base
  database: feeder_production
