base: &base
  user: postgres
  password: postgres
  host: postgres
  port: 5432

dev:
  <<: *base
  database: dogood_dev

test:
  <<: *base
  database: dogood_test

production:
  <<: *base
  database: dogood
