sources:
  - url: http://cnn.com
    publisher: CNN
  - url: http://vox.com
    publisher: Vox
  - url: http://abcnews.go.com
    publisher: ABC
  - url: http://huffingtonpost.com
    publisher: Huffington Post
